services:
  db:
    image: postgres:17
    container_name: eventosnorma_db
    env_file:
      - backend/.env
    environment:
      POSTGRES_DB: ${EVENTOSNORMA_DB_NAME}
      POSTGRES_USER: ${EVENTOSNORMA_DB_USER}
      POSTGRES_PASSWORD: ${EVENTOSNORMA_DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - eventos_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: eventosnorma_backend
    env_file:
      - backend/.env
    ports:
      - "5000:80"
    depends_on:
      - db
    networks:
      - eventos_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: eventosnorma_frontend
    env_file:
      - frontend/.env
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - eventos_network

networks:
  eventos_network:
    driver: bridge

volumes:
  postgres_data:
