services:
  db:
    image: postgres:17-alpine
    container_name: eventosnorma_db
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${EVENTOSNORMA_DB_NAME}
      POSTGRES_USER: ${EVENTOSNORMA_DB_USER}
      POSTGRES_PASSWORD: ${EVENTOSNORMA_DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: eventosnorma_backend
    ports:
      - "5000:80"
    env_file:
      - ./.env
    environment:
      - EVENTOSNORMA_DB_HOST=${EVENTOSNORMA_DB_HOST}
      - EVENTOSNORMA_DB_PORT=${EVENTOSNORMA_DB_PORT}
      - EVENTOSNORMA_DB_NAME=${EVENTOSNORMA_DB_NAME}
      - EVENTOSNORMA_DB_USER=${EVENTOSNORMA_DB_USER}
      - EVENTOSNORMA_DB_PASSWORD=${EVENTOSNORMA_DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: eventosnorma_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
